### PR TITLE
Changed tests to avoid truncate and decouple them a little bit

### PR DESCRIPTION
**Pull request by fdocr**
Now each test file will have to create its own data in the `before` hook and will be responsible for cleaning up in the `after` hook.

Will avoid `truncate` function from now on because of problems that might arise in the future (constraints/foreign keys).

### CODE REVIEW

**Comment by fdoxyz** [comment]
test this please

**Comment by fdoxyz** [comment]
ok to test

**Comment by fdoxyz** [comment]
retest this please

**Comment by fdoxyz** [comment]
retest this please

**Comment by fdoxyz** [comment]
test this please

**Comment by fdocr** [comment]
Jenkins setup fail :(

**Pull request closed without merging**
